#!/bin/bash
#======================================================================================
# Configure an instance of Fedora Linux to support Java development.
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 16 Jul 2014
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-java-dev-fedora"
export COMMON_DIR="provision-fedora-common"

mkdir -p bin
git clone "git://github.com/neopragma/$COMMON_DIR"

echo
echo '============================================================='
echo 'Applying system updates...'
"./$COMMON_DIR/apply_updates"

echo
echo '============================================================='
echo 'Installing general utilities...'
"./$COMMON_DIR/install_wget"

echo
echo '============================================================='
echo 'Installing Sublime Text 3...'
"./$COMMON_DIR/install_sublime_text_3"

echo
echo '============================================================='
echo 'Installing Microsoft TrueType fonts...'

"./$COMMON_DIR/install_msttcorefonts"

echo
echo '============================================================='
echo 'Installing Java Development Kit...'

"./$COMMON_DIR/install_openjdk7"

echo
echo '============================================================='
echo 'Installing Maven...'

"./$COMMON_DIR/install_maven"


# =============================================================
# Installing Eclipse...

"./$COMMON_DIR/install_eclipse_kepler"

echo
echo '============================================================='
echo 'Installing RVM, Ruby, and Bundler...'

"./$COMMON_DIR/install_rvm"

echo
echo '============================================================='
echo 'Setting the desktop background image...'

mkdir -p "$HOME/.backgrounds"
cp -f java-background.png "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/neopragma/.backgrounds/java-background.png

./verify


