#!/bin/bash
#======================================================================================
# Apply system updates - Fedora
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 03-July-2014
# Author: Dave Nicolette
#======================================================================================

sudo yum update

