#!/bin/bash
#======================================================================================
# Install Maven on Fedora
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 16-July-2014
# Author: Dave Nicolette
#======================================================================================

wget http://mirrors.gigenet.com/apache/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
sudo tar -zxf apache-maven-3.0.5-bin.tar.gz -C /opt/ 

sudo cat ./provision-fedora-common/maven_bashrc_entries >> ~/.bashrc


 

